# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clusterwise Linear Regression
#'
#' This is a bare-bones function and must NOT be used by an end-user.
#'
#' @param U random membership matrix.
#' @param X data matrix of dimension \code{N} by \code{P}.
#' @param y response vector of length \code{N}.
#' @param m fuzzier exponent. Gives a hard k-partition if \code{m = 1.0} and
#'   a fuzzy k-partition when \code{m > 1.0}.
#' @param itermax the maximum number of iterations allowed in Lloyd algorithm.
#' @param trace logical value. If \code{TRUE}, produce a trace information of
#'   the progress of the algorithm.
#'
#' @return returns an object of class \code{WCLR.clr}.
#'
#' @seealso \code{\link{clr.default}} for a user-friendly version of this method.
#'
#' @export
clr_lloyd_cpp <- function(U, X, y, m, itermax, trace) {
    .Call('_WCLR_clr_lloyd_cpp', PACKAGE = 'WCLR', U, X, y, m, itermax, trace)
}

#' K-means Linear Regression
#'
#' This is a bare-bones function and must NOT be used by an end-user.
#'
#' @inheritParams clr_lloyd_cpp
#'
#' @return returns an object of class \code{WCLR.kmeans}.
#'
#' @seealso \code{\link{kmeans.default}} for a user-friendly version of this method.
#'
#' @export
kmeans_lloyd_cpp <- function(U, X, y, m, itermax, trace) {
    .Call('_WCLR_kmeans_lloyd_cpp', PACKAGE = 'WCLR', U, X, y, m, itermax, trace)
}

#' K-plane Regression
#'
#' This is a bare-bones function and must NOT be used by an end-user.
#'
#' @inheritParams clr_lloyd_cpp
#' @param gamma numeric balancing value.
#'
#' @return returns an object of class \code{WCLR.kplane}.
#'
#' @seealso \code{\link{kplane.default}} for a user-friendly version of this method.
#'
#' @export
kplane_lloyd_cpp <- function(U, X, y, gamma, m, itermax, trace) {
    .Call('_WCLR_kplane_lloyd_cpp', PACKAGE = 'WCLR', U, X, y, gamma, m, itermax, trace)
}

#' Weighted Clusterwise Linear Regression
#'
#' This is a bare-bones function and must NOT be used by an end-user.
#'
#' @inheritParams clr_lloyd_cpp
#' @param alpha numeric balancing value.
#' @param wnorm wnorm type. One of: \code{"epg"}, \code{"epl"},
#'   \code{"qpg"}, \code{"qpl"}.
#'
#' @return returns an object of class \code{WCLR.wclr}.
#'
#' @seealso \code{\link{wclr.default}} for a user-friendly version of this method.
#'
#' @export
wclr_lloyd_cpp <- function(U, X, y, alpha, m, wnorm, itermax, trace) {
    .Call('_WCLR_wclr_lloyd_cpp', PACKAGE = 'WCLR', U, X, y, alpha, m, wnorm, itermax, trace)
}

#' Self-balanced Weighted Clusterwise Linear Regression
#'
#' This is a bare-bones function and must NOT be used by an end-user.
#'
#' @inheritParams clr_lloyd_cpp
#' @param wnorm wnorm type. One of: \code{"epg"}, \code{"epl"},
#'   \code{"qpg"}, \code{"qpl"}.
#' @param balance self-balance type. One of: \code{"pg"}, \code{"pl"}.
#'
#' @return returns an object of class \code{WCLR.swclr}.
#'
#' @seealso \code{\link{swclr.default}} for a user-friendly version of this method.
#'
#' @export
swclr_lloyd_cpp <- function(U, X, y, m, wnorm, balance, itermax, trace) {
    .Call('_WCLR_swclr_lloyd_cpp', PACKAGE = 'WCLR', U, X, y, m, wnorm, balance, itermax, trace)
}

#' Predict
#'
#' Predict values by nearest Euclidean distance.
#'
#' @param X newdata matrix
#' @param C centers matrix
#' @param R coefficients matrix
#' @param m fuzzier exponent
#'
#' @return a vector of predictions.
#'
#' @export
predict_euclidean_cpp <- function(X, C, R, m) {
    .Call('_WCLR_predict_euclidean_cpp', PACKAGE = 'WCLR', X, C, R, m)
}

#' Predict
#'
#' Predict values by nearest quadratic distance.
#'
#' @param X newdata matrix
#' @param C centers matrix
#' @param W weights cube
#' @param R coefficients matrix
#' @param m fuzzier exponent
#'
#' @return a vector of predictions.
#'
#' @export
predict_quadratic_cpp <- function(X, C, W, R, m) {
    .Call('_WCLR_predict_quadratic_cpp', PACKAGE = 'WCLR', X, C, W, R, m)
}

